# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/programming.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(40, 40, 40)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Menu = QtWidgets.QTabWidget(self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setBold(True)
        font.setWeight(75)
        self.Menu.setFont(font)
        self.Menu.setAutoFillBackground(False)
        self.Menu.setStyleSheet("QTabBar::tab {\n"
"    min-width: 70px;\n"
"    min-height: 50px;\n"
"    background-color : rgb(55, 59, 71)\n"
"}\n"
"QTabBar::tab::selected {\n"
"    background-color: rgb(108, 120, 147);\n"
"}\n"
"QTabBar{\n"
"background-color : rgb(55, 59, 71);\n"
"}")
        self.Menu.setTabPosition(QtWidgets.QTabWidget.West)
        self.Menu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Menu.setIconSize(QtCore.QSize(25, 25))
        self.Menu.setElideMode(QtCore.Qt.ElideLeft)
        self.Menu.setDocumentMode(True)
        self.Menu.setMovable(False)
        self.Menu.setObjectName("Menu")
        self.About_tab = QtWidgets.QWidget()
        self.About_tab.setObjectName("About_tab")
        self.welcom_label = QtWidgets.QLabel(self.About_tab)
        self.welcom_label.setGeometry(QtCore.QRect(290, 0, 675, 141))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.welcom_label.setFont(font)
        self.welcom_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.welcom_label.setStyleSheet("color : rgb(255, 244, 233)")
        self.welcom_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.welcom_label.setObjectName("welcom_label")
        self.version_label = QtWidgets.QLabel(self.About_tab)
        self.version_label.setGeometry(QtCore.QRect(140, 150, 131, 51))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.version_label.setFont(font)
        self.version_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.version_label.setStyleSheet("color : rgb(255, 244, 233)")
        self.version_label.setWordWrap(True)
        self.version_label.setObjectName("version_label")
        self.bilders_label = QtWidgets.QLabel(self.About_tab)
        self.bilders_label.setGeometry(QtCore.QRect(320, 150, 361, 51))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.bilders_label.setFont(font)
        self.bilders_label.setStyleSheet("color :  rgb(255, 244, 233)")
        self.bilders_label.setObjectName("bilders_label")
        self.school_label = QtWidgets.QLabel(self.About_tab)
        self.school_label.setGeometry(QtCore.QRect(730, 150, 371, 51))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(18)
        self.school_label.setFont(font)
        self.school_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.school_label.setStyleSheet("color :  rgb(255, 244, 233)")
        self.school_label.setWordWrap(True)
        self.school_label.setObjectName("school_label")
        self.about_laber = QtWidgets.QLabel(self.About_tab)
        self.about_laber.setGeometry(QtCore.QRect(130, 240, 981, 431))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.about_laber.setFont(font)
        self.about_laber.setStyleSheet("color :  rgb(255, 244, 233)")
        self.about_laber.setWordWrap(True)
        self.about_laber.setObjectName("about_laber")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/24x24/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.addTab(self.About_tab, icon1, "")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.charge_label_home = QtWidgets.QLabel(self.Home)
        self.charge_label_home.setGeometry(QtCore.QRect(1050, 80, 50, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(14)
        self.charge_label_home.setFont(font)
        self.charge_label_home.setStyleSheet("color : rgb(255,244,233)")
        self.charge_label_home.setObjectName("charge_label_home")
        self.coin_icon_home = QtWidgets.QLabel(self.Home)
        self.coin_icon_home.setGeometry(QtCore.QRect(1120, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.coin_icon_home.setFont(font)
        self.coin_icon_home.setStyleSheet("color : rgb(255,244,233)")
        self.coin_icon_home.setText("")
        self.coin_icon_home.setTextFormat(QtCore.Qt.AutoText)
        self.coin_icon_home.setPixmap(QtGui.QPixmap("icons/coin.png"))
        self.coin_icon_home.setObjectName("coin_icon_home")
        self.charge_icon_home = QtWidgets.QLabel(self.Home)
        self.charge_icon_home.setGeometry(QtCore.QRect(1120, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charge_icon_home.setFont(font)
        self.charge_icon_home.setStyleSheet("color : rgb(255,244,233)")
        self.charge_icon_home.setText("")
        self.charge_icon_home.setTextFormat(QtCore.Qt.AutoText)
        self.charge_icon_home.setPixmap(QtGui.QPixmap("icons/flash.png"))
        self.charge_icon_home.setObjectName("charge_icon_home")
        self.coin_label_home = QtWidgets.QLabel(self.Home)
        self.coin_label_home.setGeometry(QtCore.QRect(1050, 35, 50, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(14)
        self.coin_label_home.setFont(font)
        self.coin_label_home.setStyleSheet("color : rgb(255,244,233)")
        self.coin_label_home.setObjectName("coin_label_home")
        self.button_teach_1 = QtWidgets.QPushButton(self.Home)
        self.button_teach_1.setGeometry(QtCore.QRect(20, 29, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_1.setFont(font)
        self.button_teach_1.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_1.setObjectName("button_teach_1")
        self.button_file_1 = QtWidgets.QPushButton(self.Home)
        self.button_file_1.setGeometry(QtCore.QRect(20, 60, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_file_1.setFont(font)
        self.button_file_1.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_file_1.setObjectName("button_file_1")
        self.way_1 = QtWidgets.QLabel(self.Home)
        self.way_1.setGeometry(QtCore.QRect(71, 100, 51, 101))
        self.way_1.setText("")
        self.way_1.setPixmap(QtGui.QPixmap("icons/way.png"))
        self.way_1.setObjectName("way_1")
        self.button_teach_2 = QtWidgets.QPushButton(self.Home)
        self.button_teach_2.setGeometry(QtCore.QRect(71, 197, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_2.setFont(font)
        self.button_teach_2.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_2.setObjectName("button_teach_2")
        self.way_2 = QtWidgets.QLabel(self.Home)
        self.way_2.setGeometry(QtCore.QRect(120, 280, 81, 71))
        self.way_2.setText("")
        self.way_2.setPixmap(QtGui.QPixmap("icons/way_1.png"))
        self.way_2.setObjectName("way_2")
        self.button_practice_3 = QtWidgets.QPushButton(self.Home)
        self.button_practice_3.setGeometry(QtCore.QRect(160, 349, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_3.setFont(font)
        self.button_practice_3.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_3.setObjectName("button_practice_3")
        self.way_3 = QtWidgets.QLabel(self.Home)
        self.way_3.setGeometry(QtCore.QRect(250, 280, 101, 111))
        self.way_3.setText("")
        self.way_3.setPixmap(QtGui.QPixmap("icons/way_2.png"))
        self.way_3.setObjectName("way_3")
        self.button_teach_4 = QtWidgets.QPushButton(self.Home)
        self.button_teach_4.setGeometry(QtCore.QRect(350, 210, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_4.setFont(font)
        self.button_teach_4.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_4.setObjectName("button_teach_4")
        self.way_4 = QtWidgets.QLabel(self.Home)
        self.way_4.setGeometry(QtCore.QRect(360, 110, 101, 101))
        self.way_4.setText("")
        self.way_4.setPixmap(QtGui.QPixmap("icons/way_3.png"))
        self.way_4.setObjectName("way_4")
        self.button_practice_5 = QtWidgets.QPushButton(self.Home)
        self.button_practice_5.setGeometry(QtCore.QRect(460, 60, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_5.setFont(font)
        self.button_practice_5.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_5.setObjectName("button_practice_5")
        self.way_5 = QtWidgets.QLabel(self.Home)
        self.way_5.setGeometry(QtCore.QRect(460, 130, 101, 381))
        self.way_5.setText("")
        self.way_5.setPixmap(QtGui.QPixmap("icons/way_4.png"))
        self.way_5.setObjectName("way_5")
        self.button_practice_7 = QtWidgets.QPushButton(self.Home)
        self.button_practice_7.setGeometry(QtCore.QRect(40, 530, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_7.setFont(font)
        self.button_practice_7.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_7.setObjectName("button_practice_7")
        self.button_picture_3 = QtWidgets.QPushButton(self.Home)
        self.button_picture_3.setGeometry(QtCore.QRect(160, 382, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_3.setFont(font)
        self.button_picture_3.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_3.setObjectName("button_picture_3")
        self.button_picture_5 = QtWidgets.QPushButton(self.Home)
        self.button_picture_5.setGeometry(QtCore.QRect(460, 90, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_5.setFont(font)
        self.button_picture_5.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_5.setObjectName("button_picture_5")
        self.button_picture_7 = QtWidgets.QPushButton(self.Home)
        self.button_picture_7.setGeometry(QtCore.QRect(40, 560, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_7.setFont(font)
        self.button_picture_7.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_7.setObjectName("button_picture_7")
        self.button_teach_6 = QtWidgets.QPushButton(self.Home)
        self.button_teach_6.setGeometry(QtCore.QRect(430, 510, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_6.setFont(font)
        self.button_teach_6.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_6.setObjectName("button_teach_6")
        self.way_6 = QtWidgets.QLabel(self.Home)
        self.way_6.setGeometry(QtCore.QRect(130, 540, 301, 91))
        self.way_6.setText("")
        self.way_6.setPixmap(QtGui.QPixmap("icons/way_5.png"))
        self.way_6.setObjectName("way_6")
        self.way_7 = QtWidgets.QLabel(self.Home)
        self.way_7.setGeometry(QtCore.QRect(70, 600, 311, 61))
        self.way_7.setText("")
        self.way_7.setPixmap(QtGui.QPixmap("icons/way_6.png"))
        self.way_7.setObjectName("way_7")
        self.button_teach_8 = QtWidgets.QPushButton(self.Home)
        self.button_teach_8.setGeometry(QtCore.QRect(370, 620, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_8.setFont(font)
        self.button_teach_8.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_8.setObjectName("button_teach_8")
        self.button_practice_9 = QtWidgets.QPushButton(self.Home)
        self.button_practice_9.setGeometry(QtCore.QRect(610, 557, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_9.setFont(font)
        self.button_practice_9.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_9.setObjectName("button_practice_9")
        self.button_picture_9 = QtWidgets.QPushButton(self.Home)
        self.button_picture_9.setGeometry(QtCore.QRect(610, 590, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_9.setFont(font)
        self.button_picture_9.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_9.setObjectName("button_picture_9")
        self.way_8 = QtWidgets.QLabel(self.Home)
        self.way_8.setGeometry(QtCore.QRect(460, 600, 151, 91))
        self.way_8.setText("")
        self.way_8.setPixmap(QtGui.QPixmap("icons/way_7.png"))
        self.way_8.setObjectName("way_8")
        self.way_9 = QtWidgets.QLabel(self.Home)
        self.way_9.setGeometry(QtCore.QRect(630, 405, 101, 151))
        self.way_9.setText("")
        self.way_9.setPixmap(QtGui.QPixmap("icons/way_8.png"))
        self.way_9.setObjectName("way_9")
        self.button_teach_10 = QtWidgets.QPushButton(self.Home)
        self.button_teach_10.setGeometry(QtCore.QRect(700, 330, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_10.setFont(font)
        self.button_teach_10.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_10.setObjectName("button_teach_10")
        self.way_10 = QtWidgets.QLabel(self.Home)
        self.way_10.setGeometry(QtCore.QRect(630, 180, 91, 151))
        self.way_10.setText("")
        self.way_10.setPixmap(QtGui.QPixmap("icons/way_9.png"))
        self.way_10.setObjectName("way_10")
        self.button_practice_11 = QtWidgets.QPushButton(self.Home)
        self.button_practice_11.setGeometry(QtCore.QRect(610, 107, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_11.setFont(font)
        self.button_practice_11.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_11.setObjectName("button_practice_11")
        self.button_picture_11 = QtWidgets.QPushButton(self.Home)
        self.button_picture_11.setGeometry(QtCore.QRect(610, 140, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_11.setFont(font)
        self.button_picture_11.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_11.setObjectName("button_picture_11")
        self.way_11 = QtWidgets.QLabel(self.Home)
        self.way_11.setGeometry(QtCore.QRect(700, 100, 51, 61))
        self.way_11.setText("")
        self.way_11.setPixmap(QtGui.QPixmap("icons/way_10.png"))
        self.way_11.setObjectName("way_11")
        self.button_practice_12 = QtWidgets.QPushButton(self.Home)
        self.button_practice_12.setGeometry(QtCore.QRect(750, 80, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_12.setFont(font)
        self.button_practice_12.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_12.setObjectName("button_practice_12")
        self.button_picture_12 = QtWidgets.QPushButton(self.Home)
        self.button_picture_12.setGeometry(QtCore.QRect(750, 113, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_12.setFont(font)
        self.button_picture_12.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_12.setObjectName("button_picture_12")
        self.way_12 = QtWidgets.QLabel(self.Home)
        self.way_12.setGeometry(QtCore.QRect(790, 154, 101, 111))
        self.way_12.setText("")
        self.way_12.setPixmap(QtGui.QPixmap("icons/way_11.png"))
        self.way_12.setObjectName("way_12")
        self.button_teach_13 = QtWidgets.QPushButton(self.Home)
        self.button_teach_13.setGeometry(QtCore.QRect(850, 250, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_13.setFont(font)
        self.button_teach_13.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_13.setObjectName("button_teach_13")
        self.way_18 = QtWidgets.QLabel(self.Home)
        self.way_18.setGeometry(QtCore.QRect(820, 330, 81, 101))
        self.way_18.setText("")
        self.way_18.setPixmap(QtGui.QPixmap("icons/way_12.png"))
        self.way_18.setObjectName("way_18")
        self.button_practice_14 = QtWidgets.QPushButton(self.Home)
        self.button_practice_14.setGeometry(QtCore.QRect(810, 427, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_14.setFont(font)
        self.button_practice_14.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_14.setObjectName("button_practice_14")
        self.button_picture_14 = QtWidgets.QPushButton(self.Home)
        self.button_picture_14.setGeometry(QtCore.QRect(810, 460, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_14.setFont(font)
        self.button_picture_14.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_14.setObjectName("button_picture_14")
        self.way_14 = QtWidgets.QLabel(self.Home)
        self.way_14.setGeometry(QtCore.QRect(780, 500, 91, 111))
        self.way_14.setText("")
        self.way_14.setPixmap(QtGui.QPixmap("icons/way_13.png"))
        self.way_14.setObjectName("way_14")
        self.button_teach_15 = QtWidgets.QPushButton(self.Home)
        self.button_teach_15.setGeometry(QtCore.QRect(740, 600, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_15.setFont(font)
        self.button_teach_15.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_15.setObjectName("button_teach_15")
        self.way_16 = QtWidgets.QLabel(self.Home)
        self.way_16.setGeometry(QtCore.QRect(930, 520, 81, 101))
        self.way_16.setText("")
        self.way_16.setPixmap(QtGui.QPixmap("icons/way_12.png"))
        self.way_16.setObjectName("way_16")
        self.button_practice_16 = QtWidgets.QPushButton(self.Home)
        self.button_practice_16.setGeometry(QtCore.QRect(880, 577, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_16.setFont(font)
        self.button_practice_16.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_16.setObjectName("button_practice_16")
        self.button_picture_16 = QtWidgets.QPushButton(self.Home)
        self.button_picture_16.setGeometry(QtCore.QRect(880, 610, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_16.setFont(font)
        self.button_picture_16.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_16.setObjectName("button_picture_16")
        self.way_15 = QtWidgets.QLabel(self.Home)
        self.way_15.setGeometry(QtCore.QRect(830, 600, 51, 61))
        self.way_15.setText("")
        self.way_15.setPixmap(QtGui.QPixmap("icons/way_10.png"))
        self.way_15.setObjectName("way_15")
        self.button_picture_17 = QtWidgets.QPushButton(self.Home)
        self.button_picture_17.setGeometry(QtCore.QRect(940, 493, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_17.setFont(font)
        self.button_picture_17.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_picture_17.setObjectName("button_picture_17")
        self.button_practice_17 = QtWidgets.QPushButton(self.Home)
        self.button_practice_17.setGeometry(QtCore.QRect(940, 460, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_17.setFont(font)
        self.button_practice_17.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_practice_17.setObjectName("button_practice_17")
        self.way_17 = QtWidgets.QLabel(self.Home)
        self.way_17.setGeometry(QtCore.QRect(950, 360, 101, 101))
        self.way_17.setText("")
        self.way_17.setPixmap(QtGui.QPixmap("icons/way_3.png"))
        self.way_17.setObjectName("way_17")
        self.way_13 = QtWidgets.QLabel(self.Home)
        self.way_13.setGeometry(QtCore.QRect(1020, 350, 101, 111))
        self.way_13.setText("")
        self.way_13.setPixmap(QtGui.QPixmap("icons/way_11.png"))
        self.way_13.setObjectName("way_13")
        self.button_teach_18 = QtWidgets.QPushButton(self.Home)
        self.button_teach_18.setGeometry(QtCore.QRect(980, 280, 90, 80))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_teach_18.setFont(font)
        self.button_teach_18.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(93, 93, 93);\n"
"color : rgb(255,244,233)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.button_teach_18.setObjectName("button_teach_18")
        self.button_practice_19 = QtWidgets.QPushButton(self.Home)
        self.button_practice_19.setGeometry(QtCore.QRect(1120, 407, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_practice_19.setFont(font)
        self.button_practice_19.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(252, 252, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(223, 226, 0)\n"
"}")
        self.button_practice_19.setObjectName("button_practice_19")
        self.button_picture_19 = QtWidgets.QPushButton(self.Home)
        self.button_picture_19.setGeometry(QtCore.QRect(1120, 440, 90, 40))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.button_picture_19.setFont(font)
        self.button_picture_19.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color :rgb(252, 252, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(223, 226, 0)\n"
"}")
        self.button_picture_19.setObjectName("button_picture_19")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/24x24/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.addTab(self.Home, icon2, "")
        self.Store = QtWidgets.QWidget()
        self.Store.setObjectName("Store")
        self.charge3_store_button_2 = QtWidgets.QPushButton(self.Store)
        self.charge3_store_button_2.setGeometry(QtCore.QRect(330, 160, 260, 490))
        self.charge3_store_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.charge3_store_button_2.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color :rgb(93, 93, 93);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.charge3_store_button_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/store/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.charge3_store_button_2.setIcon(icon3)
        self.charge3_store_button_2.setIconSize(QtCore.QSize(490, 490))
        self.charge3_store_button_2.setObjectName("charge3_store_button_2")
        self.charge5_store_button_3 = QtWidgets.QPushButton(self.Store)
        self.charge5_store_button_3.setGeometry(QtCore.QRect(630, 160, 260, 490))
        self.charge5_store_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.charge5_store_button_3.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color :rgb(93, 93, 93);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.charge5_store_button_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/store/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.charge5_store_button_3.setIcon(icon4)
        self.charge5_store_button_3.setIconSize(QtCore.QSize(500, 500))
        self.charge5_store_button_3.setObjectName("charge5_store_button_3")
        self.charge10_store_button_4 = QtWidgets.QPushButton(self.Store)
        self.charge10_store_button_4.setGeometry(QtCore.QRect(930, 160, 260, 490))
        self.charge10_store_button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.charge10_store_button_4.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color :rgb(93, 93, 93);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.charge10_store_button_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/store/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.charge10_store_button_4.setIcon(icon5)
        self.charge10_store_button_4.setIconSize(QtCore.QSize(500, 500))
        self.charge10_store_button_4.setObjectName("charge10_store_button_4")
        self.store_title_label = QtWidgets.QLabel(self.Store)
        self.store_title_label.setGeometry(QtCore.QRect(480, 10, 251, 111))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setBold(True)
        font.setWeight(75)
        self.store_title_label.setFont(font)
        self.store_title_label.setStyleSheet("color : rgb(255, 244, 233)\n"
"")
        self.store_title_label.setObjectName("store_title_label")
        self.store_tip_label = QtWidgets.QLabel(self.Store)
        self.store_tip_label.setGeometry(QtCore.QRect(290, 710, 611, 51))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        self.store_tip_label.setFont(font)
        self.store_tip_label.setStyleSheet("color : rgb(255, 244, 233)")
        self.store_tip_label.setObjectName("store_tip_label")
        self.charge_icon_store = QtWidgets.QLabel(self.Store)
        self.charge_icon_store.setGeometry(QtCore.QRect(1120, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.charge_icon_store.setFont(font)
        self.charge_icon_store.setStyleSheet("color : rgb(255,244,233)")
        self.charge_icon_store.setText("")
        self.charge_icon_store.setTextFormat(QtCore.Qt.AutoText)
        self.charge_icon_store.setPixmap(QtGui.QPixmap("icons/flash.png"))
        self.charge_icon_store.setObjectName("charge_icon_store")
        self.coin_icon_store = QtWidgets.QLabel(self.Store)
        self.coin_icon_store.setGeometry(QtCore.QRect(1120, 30, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.coin_icon_store.setFont(font)
        self.coin_icon_store.setStyleSheet("color : rgb(255,244,233)")
        self.coin_icon_store.setText("")
        self.coin_icon_store.setTextFormat(QtCore.Qt.AutoText)
        self.coin_icon_store.setPixmap(QtGui.QPixmap("icons/coin.png"))
        self.coin_icon_store.setObjectName("coin_icon_store")
        self.coin_label_store = QtWidgets.QLabel(self.Store)
        self.coin_label_store.setGeometry(QtCore.QRect(1050, 35, 50, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(14)
        self.coin_label_store.setFont(font)
        self.coin_label_store.setStyleSheet("color : rgb(255,244,233)")
        self.coin_label_store.setObjectName("coin_label_store")
        self.charge_label_store = QtWidgets.QLabel(self.Store)
        self.charge_label_store.setGeometry(QtCore.QRect(1050, 80, 50, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(14)
        self.charge_label_store.setFont(font)
        self.charge_label_store.setStyleSheet("color : rgb(255,244,233)")
        self.charge_label_store.setObjectName("charge_label_store")
        self.charge1_store_button_1 = QtWidgets.QPushButton(self.Store)
        self.charge1_store_button_1.setGeometry(QtCore.QRect(30, 160, 260, 490))
        self.charge1_store_button_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.charge1_store_button_1.setStyleSheet("QPushButton{\n"
"border-radius: 15px;\n"
"background-color :rgb(93, 93, 93);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 80, 80)\n"
"}")
        self.charge1_store_button_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/store/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.charge1_store_button_1.setIcon(icon6)
        self.charge1_store_button_1.setIconSize(QtCore.QSize(490, 490))
        self.charge1_store_button_1.setObjectName("charge1_store_button_1")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/24x24/cil-tag.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.addTab(self.Store, icon7, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.settings_title = QtWidgets.QLabel(self.Settings)
        self.settings_title.setGeometry(QtCore.QRect(488, 10, 241, 111))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        self.settings_title.setFont(font)
        self.settings_title.setStyleSheet("color : rgb(255, 244, 233)\n"
"")
        self.settings_title.setObjectName("settings_title")
        self.Sound_label = QtWidgets.QLabel(self.Settings)
        self.Sound_label.setGeometry(QtCore.QRect(720, 170, 171, 61))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(18)
        self.Sound_label.setFont(font)
        self.Sound_label.setStyleSheet("color : rgb(255, 244, 233)")
        self.Sound_label.setObjectName("Sound_label")
        self.character_label = QtWidgets.QLabel(self.Settings)
        self.character_label.setGeometry(QtCore.QRect(770, 430, 121, 51))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.character_label.setFont(font)
        self.character_label.setStyleSheet("color : rgb(255, 244, 233)")
        self.character_label.setObjectName("character_label")
        self.boy_1 = QtWidgets.QRadioButton(self.Settings)
        self.boy_1.setGeometry(QtCore.QRect(540, 500, 121, 61))
        self.boy_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boy_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/boy_anim_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boy_1.setIcon(icon8)
        self.boy_1.setIconSize(QtCore.QSize(200, 200))
        self.boy_1.setChecked(True)
        self.boy_1.setObjectName("boy_1")
        self.boy_2 = QtWidgets.QRadioButton(self.Settings)
        self.boy_2.setGeometry(QtCore.QRect(540, 580, 121, 61))
        self.boy_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boy_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/boy2_anim_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boy_2.setIcon(icon9)
        self.boy_2.setIconSize(QtCore.QSize(200, 200))
        self.boy_2.setObjectName("boy_2")
        self.boy_3 = QtWidgets.QRadioButton(self.Settings)
        self.boy_3.setGeometry(QtCore.QRect(540, 660, 121, 61))
        self.boy_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.boy_3.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/boy3_anim_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boy_3.setIcon(icon10)
        self.boy_3.setIconSize(QtCore.QSize(200, 200))
        self.boy_3.setObjectName("boy_3")
        self.Sound_slider = QtWidgets.QSlider(self.Settings)
        self.Sound_slider.setGeometry(QtCore.QRect(591, 150, 61, 241))
        self.Sound_slider.setOrientation(QtCore.Qt.Vertical)
        self.Sound_slider.setObjectName("Sound_slider")
        self.Music_slider_2 = QtWidgets.QSlider(self.Settings)
        self.Music_slider_2.setGeometry(QtCore.QRect(440, 150, 61, 241))
        self.Music_slider_2.setOrientation(QtCore.Qt.Vertical)
        self.Music_slider_2.setObjectName("Music_slider_2")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/24x24/cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Menu.addTab(self.Settings, icon11, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Menu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Code Jungle"))
        self.welcom_label.setText(_translate("MainWindow", "به جنگل کد خوش آمديد"))
        self.version_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">نسخه 1.0.00</p></body></html>"))
        self.bilders_label.setText(_translate("MainWindow", "<html><head/><body><p>سازندگان: یاسین بختیار - رادین رییسی</p></body></html>"))
        self.school_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">دبیرستان : دبیرستان شهید اژه ای 2</p></body></html>"))
        self.about_laber.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">...سلام بچه ها! خوبید؟</p><p align=\"right\">حتما شنیدید که می گن توی قرن حاضر یعنی قرن یبیست و یکم ،همه باید با تکنیک های برنامه نویسی تا حدی آشنا باشند و از آن ها استفاده کنند. اما چه موقعی؟</p><p align=\"right\">معلومه!! از کودکی! به گفته برنامه نویسان مهم دنیا، کودکان باید ابتدا چگونگی <span style=\" font-weight:600;\">مثل کامپیوتر فکر کردن </span>و اصوال ابتدایی برنامه نویسی را یاد بگیرند تا در بعد ها ، بتوانند این مهارت را به صورت حرفه ای و البته به صورت ساده بیاموزند. دوباره سوال پیش می آید. چطور؟؟</p><p align=\"right\">اینم واضحه!! برای اینکار ابزار های زیادی وجود دارند که هر کدام با روش های مختلفی به کودکان برنامه نویسی یاد می دهند. از این میان، ما بهترین روش را انتخاب کردیم و با توجه به آن برای تمام کودکان و نوجوانان ایران زمین اپلیکیشنی طراحی کردیم تا کودکان در کنار تفریح، استعداد های خود را شکوفا کنند </p><p align=\"right\">بازی از این قراره که آتورپات از بس همیشه مشغول بازی های رایانه ای هست، توسط بازی بلعیده می شود و به داخل آن می رود. شما باید با برنامه نویسی به او کمک کنید تا مراحل را پشت سربگذارد و از بازی کامپیوتری خارج شود. شاید برای آتورپات عبرتی شود و وقت خود را کمتر صرف بازی های رایانه ای کند</p><p align=\"right\"><br/></p><p align=\"right\"><br/></p></body></html>"))
        self.charge_label_home.setText(_translate("MainWindow", "TextLabel"))
        self.coin_label_home.setText(_translate("MainWindow", "TextLabel"))
        self.button_teach_1.setText(_translate("MainWindow", "نصب پایتون"))
        self.button_file_1.setText(_translate("MainWindow", "فایل نصبی"))
        self.button_teach_2.setText(_translate("MainWindow", "آموزش"))
        self.button_practice_3.setText(_translate("MainWindow", "تمرین 1"))
        self.button_teach_4.setText(_translate("MainWindow", "آموزش"))
        self.button_practice_5.setText(_translate("MainWindow", "تمرین 2"))
        self.button_practice_7.setText(_translate("MainWindow", "تمرین 3"))
        self.button_picture_3.setText(_translate("MainWindow", "عکس"))
        self.button_picture_5.setText(_translate("MainWindow", "عکس"))
        self.button_picture_7.setText(_translate("MainWindow", "عکس"))
        self.button_teach_6.setText(_translate("MainWindow", "آموزش"))
        self.button_teach_8.setText(_translate("MainWindow", "آموزش"))
        self.button_practice_9.setText(_translate("MainWindow", "تمرین 4"))
        self.button_picture_9.setText(_translate("MainWindow", "عکس"))
        self.button_teach_10.setText(_translate("MainWindow", "آموزش"))
        self.button_practice_11.setText(_translate("MainWindow", "تمرین 5"))
        self.button_picture_11.setText(_translate("MainWindow", "عکس"))
        self.button_practice_12.setText(_translate("MainWindow", "تمرین 6"))
        self.button_picture_12.setText(_translate("MainWindow", "عکس"))
        self.button_teach_13.setText(_translate("MainWindow", "آموزش"))
        self.button_practice_14.setText(_translate("MainWindow", "تمرین 7"))
        self.button_picture_14.setText(_translate("MainWindow", "عکس"))
        self.button_teach_15.setText(_translate("MainWindow", "آموزش"))
        self.button_practice_16.setText(_translate("MainWindow", "تمرین 8"))
        self.button_picture_16.setText(_translate("MainWindow", "عکس"))
        self.button_picture_17.setText(_translate("MainWindow", "عکس"))
        self.button_practice_17.setText(_translate("MainWindow", "تمرین 9"))
        self.button_teach_18.setText(_translate("MainWindow", "آموزش"))
        self.button_practice_19.setText(_translate("MainWindow", "تمرين 10"))
        self.button_picture_19.setText(_translate("MainWindow", "عکس"))
        self.store_title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">فروشگاه</span></p></body></html>"))
        self.store_tip_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">نکته : قیمت این کالا ها به صورت پول داخل اپلیکیشن است نه پول واقعی</span></p></body></html>"))
        self.settings_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">تنظیمات</span></p></body></html>"))
        self.Sound_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">صدا و صوت</span></p></body></html>"))
        self.character_label.setText(_translate("MainWindow", "کاراکتر"))
        #my codes:
        self.button_teach_1.clicked.connect(self.get_teach1) # for teach 1 --> install pythgom
        self.button_file_1.clicked.connect(self.get_pythoninstaller) # for python installer -->64bit or 32bit
        self.button_teach_2.clicked.connect(self.get_teach2)# for teach 2 --> left() & front()
        self.button_teach_4.clicked.connect(self.get_teach3)# for teach 3 --> right() & behind
        self.button_teach_6.clicked.connect(self.get_teach4) #for teach --> output() and vars
        self.button_teach_8.clicked.connect(self.get_teach5) # for teach --> input() and comments
        
        self.button_practice_3.clicked.connect(self.get_level1)
        self.button_picture_3.clicked.connect(self.get_picture_1)
        self.button_picture_5.clicked.connect(self.get_picture_2)
        self.button_practice_5.clicked.connect(self.get_level2)
        #7
        self.button_practice_7.clicked.connect(self.get_level3)
        self.button_picture_7.clicked.connect(self.get_picture_3)
        #8
        self.button_teach_6.clicked.connect(self.get_teach4) #for teach --> output() and vars
        self.button_picture_9.clicked.connect(self.get_picture_4)
        self.button_practice_9.clicked.connect(self.get_level4)
        
        self.button_teach_10.clicked.connect(self.get_teach6)

        #store
        self.charge1_store_button_1.clicked.connect(self.get_store_1)
        self.charge3_store_button_2.clicked.connect(self.get_store_2)
        self.charge5_store_button_3.clicked.connect(self.get_store_3)
        self.charge10_store_button_4.clicked.connect(self.get_store_4)
        
        #connect to database:
        self.conn = sqlite3.connect('files/Game_info.db') #connect to database
        self.cur = self.conn.cursor()
        self.cur.execute("SELECT * FROM info_cc WHERE rowid=1") #for sql codes : SELECT user 's level 
        self.coin_charge = self.cur.fetchall()
        #coin
        self.coin_label_store.setText(_translate("MainWindow", str(self.coin_charge[0][0])))
        self.coin_label_home.setText(_translate("MainWindow", str(self.coin_charge[0][0])))
        
        self.charge_label_store.setText(_translate("MainWindow", str(self.coin_charge[0][1])))
        self.charge_label_home.setText(_translate("MainWindow", str(self.coin_charge[0][1])))

        #settings
        self.cur.execute("SELECT * FROM info_setting WHERE rowid=1") #for sql codes : SELECT user 's level 
        self.setting = self.cur.fetchall()
        self.Sound_slider.setValue(self.setting[0][1])
        self.Music_slider_2.setValue(self.setting[0][0])
        if self.setting[0][2] == 1:
            self.boy_1.setChecked(True)
            self.boy_2.setChecked(False)
            self.boy_3.setChecked(False)
            
        if self.setting[0][2] == 2:
            self.boy_1.setChecked(False)
            self.boy_2.setChecked(True)
            self.boy_3.setChecked(False)
            
        if self.setting[0][2] == 3:
            self.boy_1.setChecked(False)
            self.boy_2.setChecked(False)
            self.boy_3.setChecked(True)
        
        #change value
        self.Sound_slider.valueChanged[int].connect(self.sound_slider_cv)
        self.Music_slider_2.valueChanged[int].connect(self.music_slider_cv)
        self.boy_1.toggled.connect(self.boy_1_tc)
        self.boy_2.toggled.connect(self.boy_2_tc)
        self.boy_3.toggled.connect(self.boy_3_tc)











        
